name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Compactar projeto em ZIP
        run: |
          zip -r projetozipado.zip . -x "venv/*" ".git/*" ".github/*"

      - name: Upload do artefato (ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: projeto-compactado
          path: projetozipado.zip

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Baixar artefato (ZIP)
        uses: actions/download-artifact@v4
        with:
          name: projeto-compactado  # Nome correto do artefato gerado

      - name: Exibir estrutura dos arquivos baixados
        run: ls -R

  docker:
    needs: deliver
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v3
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: user/app:latest
