name: CI FastAPI Megadeth

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código do repositório
        uses: actions/checkout@v3

      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn requests pytest coverage pylint httpx

      - name: Lint com pylint
        run: pylint ./main.py ./test_api.py

      - name: Executar testes com cobertura
        run: |
          coverage run -m pytest
          coverage xml

      - name: Upload cobertura para Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          fail_ci_if_error: true